apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: main-ctr
      image: junrillg/express-app:latest
      ports:
        - containerPort: 80
    - name: helper-ctr
      image: nginx/nginx-prometheus-exporter
      args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
      ports:
        - containerPort: 9113
